Feat/add pure template
masastack/MASA.Template pull request #11
Opened 2023-04-04 03:04 UTC by MapleWithoutWords

增加了三个模板，它们的名称从上之下为：MasaBpEmpty(短名：masabpe)、MasaFxCqrsService（短名：masafxpcqrs）、MasaFxService（masafxp）
![image](https://user-images.githubusercontent.com/38368335/229675470-bfbb94ec-56c4-4f65-9bb2-d26721134243.png)
* MasaBpEmpty
![image](https://user-images.githubusercontent.com/38368335/229676018-d4246579-c283-42a1-8e71-21c6ea829ffa.png)

* MasaFxCqrsService
![image](https://user-images.githubusercontent.com/38368335/229676350-d7bbe27c-463e-40e9-9361-38f31a92836e.png)

* MasaFxService
![image](https://user-images.githubusercontent.com/38368335/229676426-9d83e749-ac15-47f2-9530-1c104bfd0672.png)

2023-04-04 05:35 UTC, doddgu commented
MasaBp-Empty -> BlazorPure, 并且短名为 masab-pure
MasaFx-Service-Cqrs -> FrameworkServiceCqrs，短名为 masafxsp
MasaFx-Service -> FrameworkService，短名为 masafxs

2023-04-04 05:36 UTC, doddgu commented
@zhenlei520 PTAL

2023-04-04 11:23 UTC, zhenlei520 commented on src/Content/BlazorPure/src/BlazorPure.WebServer/Program.cs
> +
删除换行

2023-04-04 12:19 UTC, zhenlei520 requested changes

2023-04-04 12:19 UTC, zhenlei520 commented on src/Content/FrameworkServiceCqrs/src/FrameworkServiceCqrs.Service/Application/Example/Commands/CreateExampleCommand.cs
> +﻿using FrameworkServiceCqrs.Contracts.Example;
use global using

2023-04-04 12:19 UTC, zhenlei520 commented on src/Content/FrameworkServiceCqrs/src/FrameworkServiceCqrs.Service/Application/Example/Commands/DeleteExampleCommand.cs
> +using FrameworkServiceCqrs.Contracts.Example;
use global using

2023-04-04 12:19 UTC, zhenlei520 commented on src/Content/FrameworkServiceCqrs/src/FrameworkServiceCqrs.Service/Application/Example/ExampleQueryHandler.cs
> +
删除多余换行

2023-04-04 12:19 UTC, zhenlei520 commented on src/Content/FrameworkServiceCqrs/src/FrameworkServiceCqrs.Service/Domain/FrameworkServiceCqrsDbContext.cs
> +    protected override void OnModelCreatingConfigureGlobalFilters(ModelBuilder modelBuilder)
Use OnModelCreatingExecuting

2023-04-04 12:19 UTC, zhenlei520 commented on src/Content/FrameworkServiceCqrs/src/FrameworkServiceCqrs.Service/FrameworkServiceCqrs.Service.csproj
> +		<PackageReference Include="Masa.Contrib.Data.Mapping.Mapster" Version="$(MASAFrameworkVersion)" />
format code

2023-04-04 12:19 UTC, zhenlei520 commented on src/Content/FrameworkServiceCqrs/src/FrameworkServiceCqrs.Service/Program.cs
> +    .AddSwaggerGen(c =>
swaggerGenOptions 或者 options代替无意义的参数c

2023-04-04 12:19 UTC, zhenlei520 commented on src/Content/FrameworkServiceCqrs/src/FrameworkServiceCqrs.Service/Program.cs
> +#region MigrationDb
增加换行

2023-04-04 12:19 UTC, zhenlei520 commented on src/Content/FrameworkServiceCqrs/src/FrameworkServiceCqrs.Service/Program.cs
> +if (app.Environment.IsDevelopment())
增加换行

2023-04-04 12:19 UTC, zhenlei520 commented on src/Content/FrameworkServiceCqrs/src/FrameworkServiceCqrs.Service/Services/ExampleService.cs
> +        ExampleGetListQuery query = new ExampleGetListQuery(keyword, sort, pageIndex, pageDataCount);
use var

2023-04-04 12:19 UTC, zhenlei520 commented on src/Content/FrameworkServiceCqrs/src/FrameworkServiceCqrs.Service/_Import.cs
> +global using Microsoft.EntityFrameworkCore;
global using sort

2023-04-06 13:39 UTC, capdiem requested changes

2023-04-06 13:39 UTC, capdiem commented on src/Content/BlazorPure/.template.config/template.json
> +  "description": "A project template for creating an application with Masa Contrib.",
Masa Contrib?

2023-04-06 13:39 UTC, capdiem commented on src/Content/BlazorPure/.template.config/template.json
> +  "identity": "Masa.Framework.Template",
Masa.Framework?

2023-04-06 13:39 UTC, capdiem commented on src/Content/BlazorPure/src/BlazorPure.WebServer/BlazorPure.WebServer.csproj
> +  	<PackageReference Include="Masa.Blazor" Version="$(MASABlazorVersion)" />
缩进

2023-04-06 13:39 UTC, capdiem commented on src/Content/BlazorPure/src/BlazorPure.WebServer/wwwroot/css/site.css
`#blazor-error-ui` 和 `.blazor-error-boundary` 这些CSS呢？

2023-04-06 13:39 UTC, capdiem commented on src/Content/BlazorPure/src/BlazorPure.WebServer/MainLayout.razor
> +<Masa.Blazor.MApp> @Body </Masa.Blazor.MApp>
需要global usings: __Imports.razor_

2023-04-06 13:40 UTC, capdiem commented
@MapleWithoutWords 建议你在 .NET7 的 BlazorServer Empty 模板上做修改，只需要增加必要的一些代码。

2023-04-06 14:59 UTC, zhenlei520 requested changes

2023-04-06 14:59 UTC, zhenlei520 commented on src/Content/BlazorPure/Directory.Build.props
> +  	<MASABlazorVersion>1.0.0-preview.11</MASABlazorVersion>
format code

2023-04-06 14:59 UTC, zhenlei520 commented on src/Content/FrameworkService/.template.config/template.json
> +  "description": "A project template for creating an application with Masa Contrib.",
?

2023-04-06 14:59 UTC, zhenlei520 commented on src/Content/FrameworkService/Directory.Build.props
> +  	<MASAFrameworkVersion>1.0.0-preview.26</MASAFrameworkVersion>
format code

2023-04-06 14:59 UTC, zhenlei520 commented on src/Content/FrameworkService/src/MasaFxService.Service/FrameworkService.Service.csproj
> +  	<PackageReference Include="Masa.Contrib.Service.MinimalAPIs" Version="$(MASAFrameworkVersion)" />
format code

2023-04-06 14:59 UTC, zhenlei520 commented on src/Content/FrameworkService/src/MasaFxService.Service/Program.cs
> +builder.Services.AddEndpointsApiExplorer()
format code

2023-04-06 14:59 UTC, zhenlei520 commented on src/Content/FrameworkService/src/MasaFxService.Service/Program.cs
> +    .AddSwaggerGen(c =>
c?

2023-04-06 14:59 UTC, zhenlei520 commented on src/Content/FrameworkService/src/MasaFxService.Service/Program.cs
> +if (app.Environment.IsDevelopment())
use ```{}```？

2023-04-06 14:59 UTC, zhenlei520 commented on src/Content/FrameworkServiceCqrs/.template.config/template.json
> +  "description": "A project template for creating an application with Masa Contrib.",
？

2023-04-06 14:59 UTC, zhenlei520 commented on src/Content/FrameworkServiceCqrs/Directory.Build.props
> +		<MASAFrameworkVersion>1.0.0-preview.26</MASAFrameworkVersion>
format code

2023-04-06 14:59 UTC, zhenlei520 commented on src/Content/FrameworkServiceCqrs/src/FrameworkServiceCqrs.Service/Application/Example/Commands/CreateExampleCommand.cs
> +﻿using FrameworkServiceCqrs.Contracts.Example;
?

2023-04-06 14:59 UTC, zhenlei520 commented on src/Content/FrameworkServiceCqrs/src/FrameworkServiceCqrs.Service/Application/Example/Commands/DeleteExampleCommand.cs
> +using FrameworkServiceCqrs.Contracts.Example;
？

2023-04-06 14:59 UTC, zhenlei520 commented on src/Content/FrameworkServiceCqrs/src/FrameworkServiceCqrs.Service/Application/Example/Commands/UpdateExampleCommand.cs
> +﻿using FrameworkServiceCqrs.Contracts.Example;
use global using

2023-04-06 14:59 UTC, zhenlei520 commented on src/Content/FrameworkServiceCqrs/src/FrameworkServiceCqrs.Service/Application/Example/Queries/ExampleGetListQuery.cs
> +﻿using FrameworkServiceCqrs.Contracts.Example;
use global using

2023-04-06 14:59 UTC, zhenlei520 commented on src/Content/FrameworkServiceCqrs/src/FrameworkServiceCqrs.Service/Application/readme.txt
> +﻿
?

2023-04-06 14:59 UTC, zhenlei520 commented on src/Content/FrameworkServiceCqrs/src/FrameworkServiceCqrs.Service/Domain/Entities/readme.txt
> +﻿
?

2023-04-06 14:59 UTC, zhenlei520 commented on src/Content/FrameworkServiceCqrs/src/FrameworkServiceCqrs.Service/Domain/FrameworkServiceCqrsDbContext.cs
> +{
Try a more meaningful name?

2023-04-06 14:59 UTC, zhenlei520 commented on src/Content/FrameworkServiceCqrs/src/FrameworkServiceCqrs.Service/FrameworkServiceCqrs.Service.csproj
> +	<ItemGroup>
format code

2023-04-06 14:59 UTC, zhenlei520 commented on src/Content/FrameworkServiceCqrs/src/FrameworkServiceCqrs.Service/FrameworkServiceCqrs.Service.csproj
> +
remove extra blank lines

2023-04-06 14:59 UTC, zhenlei520 commented on src/Content/FrameworkServiceCqrs/src/FrameworkServiceCqrs.Service/Program.cs
> +    .AddSwaggerGen(c =>
？

2023-04-06 14:59 UTC, zhenlei520 commented on src/Content/FrameworkServiceCqrs/src/FrameworkServiceCqrs.Service/Program.cs
> +if (app.Environment.IsDevelopment())
use ```{}```？

2023-04-06 14:59 UTC, zhenlei520 commented on src/Content/FrameworkServiceCqrs/src/FrameworkServiceCqrs.Service/Services/readme.txt
> +﻿// add minimal api to this.
？

2023-04-06 14:59 UTC, zhenlei520 commented on src/Content/FrameworkServiceCqrs/src/FrameworkServiceCqrs.Service/_Import.cs
> +global using Masa.BuildingBlocks.ReadWriteSplitting.Cqrs.Commands;
global using sort

2023-04-10 06:10 UTC, doddgu commented
> @MapleWithoutWords @doddgu
> 
> 1. 为什么不拆成三个PR？
> 2. 官方BlazorServer Empty项目的短名称是 blazorserver-empty，建议一致。

可以，那就保持一直吧。否则pro和pure都是p开头也容易混淆
@MapleWithoutWords

2023-04-14 08:36 UTC, MapleWithoutWords commented
> > @MapleWithoutWords @doddgu
> > 
> > 1. 为什么不拆成三个PR？
> > 2. 官方BlazorServer Empty项目的短名称是 blazorserver-empty，建议一致。
> 
> 可以，那就保持一直吧。否则pro和pure都是p开头也容易混淆 @MapleWithoutWords

跟官方保持一致，到时候名称会不会冲突，导致不显示?@doddgu @capdiem

2023-04-14 08:44 UTC, zhenlei520 commented
> 跟官方保持一致，到时候名称会不会冲突，导致不显示?@doddgu @capdiem

前面加个masa？

2023-04-14 08:51 UTC, MapleWithoutWords commented
![image](https://user-images.githubusercontent.com/38368335/231994050-36200884-b081-43d2-a3a4-d52349cfd18e.png)
我觉得，顺序要跟官方保持一致。官方名称叫：blazorserver-empty。我们就算在前面加masa，那也应该是：masablazor-server-emtpy才对。masablazor-empty-server这个名称感觉按照英文都不顺

2023-04-14 11:04 UTC, doddgu commented
> ![image](https://user-images.githubusercontent.com/38368335/231994050-36200884-b081-43d2-a3a4-d52349cfd18e.png) 我觉得，顺序要跟官方保持一致。官方名称叫：blazorserver-empty。我们就算在前面加masa，那也应该是：masablazor-server-emtpy才对。masablazor-empty-server这个名称感觉按照英文都不顺

ok

2023-04-18 08:39 UTC, zhenlei520 commented
> MasaBp-Empty -> BlazorPure, 并且短名为 masab-pure MasaFx-Service-Cqrs -> FrameworkServiceCqrs，短名为 masafxsp MasaFx-Service -> FrameworkService，短名为 masafxs

masa framework 缩写为masafx没有问题，但模版名应该能反应其意图，否则这将不利于后期记忆

2023-04-18 08:43 UTC, zhenlei520 commented
@MapleWithoutWords 应该有一个简易的图反应每个模版的作用以及对应的技术栈，新建一个issues并关联到当前的pr，确保后续追踪

2023-04-19 02:57 UTC, zhenlei520 requested changes
检查之前已经被关闭问题，重新再检查一遍

2023-04-19 02:57 UTC, zhenlei520 commented on src/Content/FrameworkService/.template.config/dotnetcli.host.json
> +    "UseProgramMain": {
有什么作用？

2023-04-19 02:57 UTC, zhenlei520 commented on src/Content/FrameworkService/Properties/launchSettings.json
> +      "launchBrowser": true,
增加判断使用Swagger后新增`launchUrl`

2023-04-19 02:57 UTC, zhenlei520 commented on src/Content/FrameworkServiceCqrs/.template.config/dotnetcli.host.json
> +    ""
?

2023-04-19 02:57 UTC, zhenlei520 commented on src/Content/FrameworkServiceCqrs/.template.config/template.json
> +        }
NET6.0、NET7.0、.NET8.0

2023-04-19 02:57 UTC, zhenlei520 commented on src/Content/FrameworkServiceCqrs/.template.config/template.json
> +      "displayName": "Do not use _top-level statements",
Dont't？

2023-04-19 02:57 UTC, zhenlei520 commented on src/Content/FrameworkServiceCqrs/src/FrameworkServiceCqrs.Service/Application/Example/Commands/DeleteExampleCommand.cs
> +using FrameworkServiceCqrs.Contracts.Example;
？

2023-04-19 02:57 UTC, zhenlei520 commented on src/Content/FrameworkServiceCqrs/src/FrameworkServiceCqrs.Service/Application/Example/Commands/UpdateExampleCommand.cs
> +﻿using FrameworkServiceCqrs.Contracts.Example;
？

2023-04-19 02:57 UTC, zhenlei520 commented on src/Content/FrameworkServiceCqrs/src/FrameworkServiceCqrs.Service/DataAccess/FrameworkServiceCqrsDbContext.cs
> +        base.OnModelCreatingConfigureGlobalFilters(modelBuilder);
？

2023-04-19 02:57 UTC, zhenlei520 commented on src/Content/FrameworkServiceCqrs/src/FrameworkServiceCqrs.Service/FrameworkServiceCqrs.Service.csproj
> +	  <PackageReference Include="Masa.Contrib.Data.EFCore.SqlServer" Version="$(MASAFrameworkVersion)" />
![image](https://user-images.githubusercontent.com/9740886/232953626-9403ac38-4560-46ec-be0a-ef31e7bcf489.png)

2023-04-19 02:57 UTC, zhenlei520 commented on src/Content/FrameworkServiceCqrs/src/FrameworkServiceCqrs.Service/Program.Main.cs
> +
删除多余换行，只保留一个换行

2023-04-19 02:57 UTC, zhenlei520 commented on src/Content/FrameworkServiceCqrs/src/FrameworkServiceCqrs.Service/Program.Main.cs
> +            .AddMasaDbContext<FrameworkServiceCqrsDbContext>(opt => opt.UseMySql(new MySqlServerVersion("5.7.26")))   //opt.UseSqlServer(),opt.UseSqlite(). more:https://docs.masastack.com/framework/b
不支持其它database？

2023-04-19 02:57 UTC, zhenlei520 commented on src/Content/FrameworkServiceCqrs/src/FrameworkServiceCqrs.Service/_Import.cs
> +global using Masa.BuildingBlocks.ReadWriteSplitting.Cqrs.Commands;
全局引用排序

2023-04-19 02:57 UTC, zhenlei520 commented on src/Content/FrameworkServiceCqrs/src/FrameworkServiceCqrs.Service/Program.cs
> +
删除多余换行

2023-04-19 02:57 UTC, zhenlei520 commented on src/Content/FrameworkServiceCqrs/src/FrameworkServiceCqrs.Service/Program.cs
> +    app.MapGet("/", async next => next.Response.Redirect("/swagger"));
将跳转到swagger通过launchSettings配置，另外接口`app.MapGet(“/”, ()=> "Hello MASA Framework")`是必须的，它不受Swaager的影响

2023-04-19 02:57 UTC, zhenlei520 commented on src/Content/FrameworkServiceCqrs/src/FrameworkServiceCqrs.Service/Properties/launchSettings.json
> +      "applicationUrl": "http://localhost:5000",
增加Swagger配置

2023-04-19 05:23 UTC, MapleWithoutWords commented on src/Content/FrameworkService/.template.config/dotnetcli.host.json
> +    "UseProgramMain": {
官方的模板有这个，就是显示定义Program类

2023-04-19 05:24 UTC, MapleWithoutWords commented on src/Content/FrameworkServiceCqrs/.template.config/template.json
> +      "displayName": "Do not use _top-level statements",
官方模板是这样的，确定我们要改？

2023-04-19 05:44 UTC, MapleWithoutWords commented on src/Content/FrameworkServiceCqrs/src/FrameworkServiceCqrs.Service/_Import.cs
> +global using Masa.BuildingBlocks.ReadWriteSplitting.Cqrs.Commands;
![image](https://user-images.githubusercontent.com/38368335/232977697-cc2fbcf9-4b52-429f-b1fe-088fac2319b9.png)
没看明白，这个是已经排序了的啊

2023-04-19 05:52 UTC, MapleWithoutWords commented on src/Content/FrameworkService/FrameworkService.csproj
> +  	<PackageReference Include="Masa.Contrib.Service.MinimalAPIs" Version="1.0.0-preview.29" />
我这边统一使用29版本

2023-04-19 06:25 UTC, MapleWithoutWords commented on src/Content/FrameworkServiceCqrs/src/FrameworkServiceCqrs.Service/Domain/Entities/readme.txt
> +﻿
建立目录结构

2023-04-21 04:01 UTC, zhenlei520 approved these changes
LGTM

2023-04-21 08:18 UTC, doddgu requested changes

2023-04-21 08:18 UTC, doddgu commented on src/Content/FrameworkServiceCqrs/src/MasaFrameworkServiceCqrs.Service/Application/Example/ExampleCommandHandler.cs
> +    /// this use business DbContext
This

2023-04-21 08:18 UTC, doddgu commented on src/Content/FrameworkServiceCqrs/src/MasaFrameworkServiceCqrs.Service/DataAccess/MasaFrameworkServiceCqrsDbContext.cs
> +    //TODO:Add DbSet<UserEntity> to this.
`//public DbSet<UserEntity> { get; set; }`

2023-04-21 08:18 UTC, doddgu commented on src/Content/FrameworkServiceCqrs/src/MasaFrameworkServiceCqrs.Service/Program.Main.cs
> +    opt.UseSqlServer();
Format code.

2023-04-21 08:18 UTC, doddgu commented on src/Content/FrameworkServiceCqrs/src/MasaFrameworkServiceCqrs.Service/Program.Main.cs
> +        app.MapMasaMinimalAPIs();
Recommended use `AddServices()` at the end of `builder.Services()`;

2023-04-21 08:18 UTC, doddgu commented on src/Content/FrameworkServiceCqrs/src/MasaFrameworkServiceCqrs.Service/Program.Main.cs
> +if (app.Environment.IsDevelopment())
Format code.

2023-04-21 11:10 UTC, doddgu requested changes

2023-04-21 11:10 UTC, doddgu commented on src/Content/FrameworkServiceCqrs/src/MasaFrameworkServiceCqrs.Service/Program.cs
> +var app = builder.AddServices(option => option.MapHttpMethodsForUnmatched = new string[] { "Post" });
Format code.

2023-04-21 11:12 UTC, doddgu requested changes

2023-04-21 11:12 UTC, doddgu commented on src/Content/FrameworkServiceCqrs/src/MasaFrameworkServiceCqrs.Service/Program.Main.cs
> +        var app = builder.AddServices(option => option.MapHttpMethodsForUnmatched = new string[] { "Post" });
All the Services.AddXxx to a chain.

2023-04-21 11:12 UTC, doddgu commented on src/Content/FrameworkServiceCqrs/src/MasaFrameworkServiceCqrs.Service/Program.Main.cs
> +        builder.Services.AddEndpointsApiExplorer()
All the Services.AddXxx to a chain.

2023-04-24 05:18 UTC, doddgu approved these changes

2023-04-24 05:19 UTC, merged