fix:issues #29,#30,#31
masastack/MASA.Template pull request #34
Opened 2023-04-24 10:13 UTC by MapleWithoutWords

2023-04-25 11:46 UTC, MapleWithoutWords commented on src/Content/Framework/src/Services/Masa.Framework.Service/Program.MinimalAPIs.cs
> +    .AddMasaDbContext<ShopDbContext>(options =>
这个是使用基础模式，才会添加这个代码，他没有使用uow相关的东西

2023-04-25 12:40 UTC, zhenlei520 approved these changes
LGTM

2023-04-26 03:44 UTC, doddgu requested changes

2023-04-26 03:44 UTC, doddgu commented on README.md
> +* masafx-service: MASA Framework pure Template (Minimal Api)
pure -> Pure or Empty

2023-04-26 03:44 UTC, doddgu commented on src/Content/Framework/src/Services/Masa.Framework.Service/Application/Handlers/OrderEventHandler.cs
> +#if (!HasDdd)
HasDDD == true, 这里就只又一个namespace了？

2023-04-27 07:15 UTC, doddgu requested changes

2023-04-27 07:15 UTC, doddgu commented on README.md
> +* masafx-service: MASA Framework Pure Or Empty Template (Minimal Api)
/.

2023-04-27 07:15 UTC, doddgu commented on src/Content/Framework/src/Services/Masa.Framework.Service/Application/Handlers/OrderEventHandler.cs
> -#if (!HasDdd)
?

2023-04-27 09:45 UTC, MapleWithoutWords commented on src/Content/Framework/src/Services/Masa.Framework.Service/Application/Handlers/OrderEventHandler.cs
> -#if (!HasDdd)
这个判断在template.json中判断，并排除这个文件

2023-04-27 10:27 UTC, doddgu requested changes

2023-04-27 10:27 UTC, doddgu commented on README.md
> +* masafx-service: MASA Framework Pure/Empty Template (Minimal Api)
?

2023-04-27 10:41 UTC, doddgu approved these changes

2023-04-27 10:41 UTC, merged